/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiCallDistributeBlockRewardSol from "./MultiCallDistributeBlockReward.sol";
export type { multiCallDistributeBlockRewardSol };
import type * as multiCallPunishSol from "./MultiCallPunish.sol";
export type { multiCallPunishSol };
export type { ProposalMockForValidators } from "./ProposalMockForValidators";
export type { PunishMockForValidator } from "./PunishMockForValidator";
export type { ReservePoolMockForValidators } from "./ReservePoolMockForValidators";
export type { ValidatorMockForProposal } from "./ValidatorMockForProposal";
export type { ValidatorMockForPunish } from "./ValidatorMockForPunish";
export type { ValidatorMockForReservePool } from "./ValidatorMockForReservePool";
