/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface PunishMockForValidatorInterface extends utils.Interface {
  functions: {
    "punish(address,bool)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "punish"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "punish",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;

  decodeFunctionResult(functionFragment: "punish", data: BytesLike): Result;

  events: {
    "CallPunish(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CallPunish"): EventFragment;
}

export interface CallPunishEventObject {
  validator: string;
  remove: boolean;
}
export type CallPunishEvent = TypedEvent<
  [string, boolean],
  CallPunishEventObject
>;

export type CallPunishEventFilter = TypedEventFilter<CallPunishEvent>;

export interface PunishMockForValidator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PunishMockForValidatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    punish(
      validator: PromiseOrValue<string>,
      remove: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  punish(
    validator: PromiseOrValue<string>,
    remove: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    punish(
      validator: PromiseOrValue<string>,
      remove: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CallPunish(address,bool)"(
      validator?: PromiseOrValue<string> | null,
      remove?: PromiseOrValue<boolean> | null
    ): CallPunishEventFilter;
    CallPunish(
      validator?: PromiseOrValue<string> | null,
      remove?: PromiseOrValue<boolean> | null
    ): CallPunishEventFilter;
  };

  estimateGas: {
    punish(
      validator: PromiseOrValue<string>,
      remove: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    punish(
      validator: PromiseOrValue<string>,
      remove: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
