/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ValidatorMockForReservePoolInterface extends utils.Interface {
  functions: {
    "lastWithdrawAmount()": FunctionFragment;
    "reservePool()": FunctionFragment;
    "setReservePool(address)": FunctionFragment;
    "withdrawBlockReward()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "lastWithdrawAmount"
      | "reservePool"
      | "setReservePool"
      | "withdrawBlockReward"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "lastWithdrawAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reservePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setReservePool",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBlockReward",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "lastWithdrawAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reservePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReservePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBlockReward",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ValidatorMockForReservePool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ValidatorMockForReservePoolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    lastWithdrawAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    reservePool(overrides?: CallOverrides): Promise<[string]>;

    setReservePool(
      pool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawBlockReward(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  lastWithdrawAmount(overrides?: CallOverrides): Promise<BigNumber>;

  reservePool(overrides?: CallOverrides): Promise<string>;

  setReservePool(
    pool: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawBlockReward(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    lastWithdrawAmount(overrides?: CallOverrides): Promise<BigNumber>;

    reservePool(overrides?: CallOverrides): Promise<string>;

    setReservePool(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawBlockReward(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    lastWithdrawAmount(overrides?: CallOverrides): Promise<BigNumber>;

    reservePool(overrides?: CallOverrides): Promise<BigNumber>;

    setReservePool(
      pool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawBlockReward(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    lastWithdrawAmount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reservePool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setReservePool(
      pool: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawBlockReward(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
