/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ValidatorMockForProposalInterface extends utils.Interface {
  functions: {
    "activeValidators(uint256)": FunctionFragment;
    "getActiveValidators()": FunctionFragment;
    "isActiveValidator(address)": FunctionFragment;
    "setActiveValidators(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "activeValidators"
      | "getActiveValidators"
      | "isActiveValidator"
      | "setActiveValidators"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activeValidators",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveValidators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveValidator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setActiveValidators",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActiveValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setActiveValidators",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ValidatorMockForProposal extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ValidatorMockForProposalInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    activeValidators(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getActiveValidators(overrides?: CallOverrides): Promise<[string[]]>;

    isActiveValidator(
      val: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setActiveValidators(
      val: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  activeValidators(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getActiveValidators(overrides?: CallOverrides): Promise<string[]>;

  isActiveValidator(
    val: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setActiveValidators(
    val: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    activeValidators(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getActiveValidators(overrides?: CallOverrides): Promise<string[]>;

    isActiveValidator(
      val: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setActiveValidators(
      val: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    activeValidators(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getActiveValidators(overrides?: CallOverrides): Promise<BigNumber>;

    isActiveValidator(
      val: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setActiveValidators(
      val: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    activeValidators(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getActiveValidators(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isActiveValidator(
      val: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setActiveValidators(
      val: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
