/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type { Params, ParamsInterface } from "../../Validators.sol/Params";

const _abi = [
  {
    inputs: [],
    name: "EPOCH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_VALIDATORS",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PROPOSAL_CONTRACT",
    outputs: [
      {
        internalType: "contract IProposal",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PUBLISH_CONTRACT",
    outputs: [
      {
        internalType: "contract IPunish",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "RESERVEPOOL_CONTRACT",
    outputs: [
      {
        internalType: "contract IReservePool",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VALIDATOR_CONTRACT",
    outputs: [
      {
        internalType: "contract IValidators",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610170806100206000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c806346f751381461006757806360c80cbf14610085578063714897df1461008d578063863a20b7146100a2578063a0dc2758146100aa578063e5a99f4f146100bf575b600080fd5b61006f6100c7565b60405161007c919061010e565b60405180910390f35b61006f6100d6565b6100956100e5565b60405161007c9190610122565b61006f6100ea565b6100b26100f9565b60405161007c9190610131565b61006f6100ff565b6033546001600160a01b031681565b6036546001600160a01b031681565b601d81565b6035546001600160a01b031681565b60375481565b6034546001600160a01b031681565b6001600160a01b0391909116815260200190565b61ffff91909116815260200190565b9081526020019056fea264697066735822122033dc9e82cd02cb64d4dab5f9ee29ed949ff835b89ea11fb2408dba2ce6a6720264736f6c634300060c0033";

type ParamsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ParamsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Params__factory extends ContractFactory {
  constructor(...args: ParamsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Params> {
    return super.deploy(overrides || {}) as Promise<Params>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Params {
    return super.attach(address) as Params;
  }
  override connect(signer: Signer): Params__factory {
    return super.connect(signer) as Params__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ParamsInterface {
    return new utils.Interface(_abi) as ParamsInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Params {
    return new Contract(address, _abi, signerOrProvider) as Params;
  }
}
