/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IProposal__factory } from "./IProposal__factory";
export { IPunish__factory } from "./IPunish__factory";
export { IReservePool__factory } from "./IReservePool__factory";
export { IValidators__factory } from "./IValidators__factory";
