/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IProposal, IProposalInterface } from "../../interfaces/IProposal";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "val",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    name: "isProposalPassed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IProposal__factory {
  static readonly abi = _abi;
  static createInterface(): IProposalInterface {
    return new utils.Interface(_abi) as IProposalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProposal {
    return new Contract(address, _abi, signerOrProvider) as IProposal;
  }
}
