/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IPunish, IPunishInterface } from "../../interfaces/IPunish";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_val",
        type: "address",
      },
    ],
    name: "punish",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPunish__factory {
  static readonly abi = _abi;
  static createInterface(): IPunishInterface {
    return new utils.Interface(_abi) as IPunishInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPunish {
    return new Contract(address, _abi, signerOrProvider) as IPunish;
  }
}
