/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IReservePool,
  IReservePoolInterface,
} from "../../interfaces/IReservePool";

const _abi = [
  {
    inputs: [],
    name: "withdrawBlockReward",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IReservePool__factory {
  static readonly abi = _abi;
  static createInterface(): IReservePoolInterface {
    return new utils.Interface(_abi) as IReservePoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReservePool {
    return new Contract(address, _abi, signerOrProvider) as IReservePool;
  }
}
