/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CallDistributeBlockRewardMultipleTimes__factory } from "./CallDistributeBlockRewardMultipleTimes__factory";
