/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface CallDistributeBlockRewardMultipleTimesInterface
  extends utils.Interface {
  functions: {
    "distributeBlockRewardMulti(uint256)": FunctionFragment;
    "validators()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "distributeBlockRewardMulti" | "validators"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "distributeBlockRewardMulti",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "validators",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "distributeBlockRewardMulti",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validators", data: BytesLike): Result;

  events: {};
}

export interface CallDistributeBlockRewardMultipleTimes extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CallDistributeBlockRewardMultipleTimesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    distributeBlockRewardMulti(
      times: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    validators(overrides?: CallOverrides): Promise<[string]>;
  };

  distributeBlockRewardMulti(
    times: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  validators(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    distributeBlockRewardMulti(
      times: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    validators(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    distributeBlockRewardMulti(
      times: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    validators(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    distributeBlockRewardMulti(
      times: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    validators(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
