/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface CallPunishMultipleTimesInterface extends utils.Interface {
  functions: {
    "punish()": FunctionFragment;
    "punishMultipleTimes(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "punish" | "punishMultipleTimes"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "punish", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "punishMultipleTimes",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "punish", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "punishMultipleTimes",
    data: BytesLike
  ): Result;

  events: {};
}

export interface CallPunishMultipleTimes extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CallPunishMultipleTimesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    punish(overrides?: CallOverrides): Promise<[string]>;

    punishMultipleTimes(
      _val: PromiseOrValue<string>,
      times: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  punish(overrides?: CallOverrides): Promise<string>;

  punishMultipleTimes(
    _val: PromiseOrValue<string>,
    times: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    punish(overrides?: CallOverrides): Promise<string>;

    punishMultipleTimes(
      _val: PromiseOrValue<string>,
      times: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    punish(overrides?: CallOverrides): Promise<BigNumber>;

    punishMultipleTimes(
      _val: PromiseOrValue<string>,
      times: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    punish(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    punishMultipleTimes(
      _val: PromiseOrValue<string>,
      times: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
