/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IProposal } from "./IProposal";
export type { IPunish } from "./IPunish";
export type { IReservePool } from "./IReservePool";
export type { IValidators } from "./IValidators";
