/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface PunishInterface extends utils.Interface {
  functions: {
    "EPOCH()": FunctionFragment;
    "MAX_VALIDATORS()": FunctionFragment;
    "PROPOSAL_CONTRACT()": FunctionFragment;
    "PUBLISH_CONTRACT()": FunctionFragment;
    "RESERVEPOOL_CONTRACT()": FunctionFragment;
    "VALIDATOR_CONTRACT()": FunctionFragment;
    "admin()": FunctionFragment;
    "changeAdmin(address)": FunctionFragment;
    "decreaseMissedBlocksCounter()": FunctionFragment;
    "decreaseRate()": FunctionFragment;
    "getPunishRecord(address)": FunctionFragment;
    "getPunishValidatorsLen()": FunctionFragment;
    "initialize(address,address,address,address,address,uint256)": FunctionFragment;
    "punish(address)": FunctionFragment;
    "punishThreshold()": FunctionFragment;
    "punishValidators(uint256)": FunctionFragment;
    "removeThreshold()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "EPOCH"
      | "MAX_VALIDATORS"
      | "PROPOSAL_CONTRACT"
      | "PUBLISH_CONTRACT"
      | "RESERVEPOOL_CONTRACT"
      | "VALIDATOR_CONTRACT"
      | "admin"
      | "changeAdmin"
      | "decreaseMissedBlocksCounter"
      | "decreaseRate"
      | "getPunishRecord"
      | "getPunishValidatorsLen"
      | "initialize"
      | "punish"
      | "punishThreshold"
      | "punishValidators"
      | "removeThreshold"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "EPOCH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_VALIDATORS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_CONTRACT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PUBLISH_CONTRACT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESERVEPOOL_CONTRACT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VALIDATOR_CONTRACT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "changeAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseMissedBlocksCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPunishRecord",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPunishValidatorsLen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "punish",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "punishThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "punishValidators",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeThreshold",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "EPOCH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VALIDATORS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_CONTRACT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PUBLISH_CONTRACT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESERVEPOOL_CONTRACT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VALIDATOR_CONTRACT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decreaseMissedBlocksCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decreaseRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPunishRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPunishValidatorsLen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "punish", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "punishThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "punishValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeThreshold",
    data: BytesLike
  ): Result;

  events: {
    "LogDecreaseMissedBlocksCounter()": EventFragment;
    "LogPunishValidator(address,uint256)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "LogDecreaseMissedBlocksCounter"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogPunishValidator"): EventFragment;
}

export interface LogDecreaseMissedBlocksCounterEventObject {}
export type LogDecreaseMissedBlocksCounterEvent = TypedEvent<
  [],
  LogDecreaseMissedBlocksCounterEventObject
>;

export type LogDecreaseMissedBlocksCounterEventFilter =
  TypedEventFilter<LogDecreaseMissedBlocksCounterEvent>;

export interface LogPunishValidatorEventObject {
  val: string;
  time: BigNumber;
}
export type LogPunishValidatorEvent = TypedEvent<
  [string, BigNumber],
  LogPunishValidatorEventObject
>;

export type LogPunishValidatorEventFilter =
  TypedEventFilter<LogPunishValidatorEvent>;

export interface Punish extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PunishInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    EPOCH(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_VALIDATORS(overrides?: CallOverrides): Promise<[number]>;

    PROPOSAL_CONTRACT(overrides?: CallOverrides): Promise<[string]>;

    PUBLISH_CONTRACT(overrides?: CallOverrides): Promise<[string]>;

    RESERVEPOOL_CONTRACT(overrides?: CallOverrides): Promise<[string]>;

    VALIDATOR_CONTRACT(overrides?: CallOverrides): Promise<[string]>;

    admin(overrides?: CallOverrides): Promise<[string]>;

    changeAdmin(
      _admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    decreaseMissedBlocksCounter(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    decreaseRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPunishRecord(
      val: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPunishValidatorsLen(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      _validatorsContract: PromiseOrValue<string>,
      _punishContract: PromiseOrValue<string>,
      _proposalContract: PromiseOrValue<string>,
      _reservePool: PromiseOrValue<string>,
      _admin: PromiseOrValue<string>,
      _epoch: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    punish(
      _val: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    punishThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    punishValidators(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    removeThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  EPOCH(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_VALIDATORS(overrides?: CallOverrides): Promise<number>;

  PROPOSAL_CONTRACT(overrides?: CallOverrides): Promise<string>;

  PUBLISH_CONTRACT(overrides?: CallOverrides): Promise<string>;

  RESERVEPOOL_CONTRACT(overrides?: CallOverrides): Promise<string>;

  VALIDATOR_CONTRACT(overrides?: CallOverrides): Promise<string>;

  admin(overrides?: CallOverrides): Promise<string>;

  changeAdmin(
    _admin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  decreaseMissedBlocksCounter(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  decreaseRate(overrides?: CallOverrides): Promise<BigNumber>;

  getPunishRecord(
    val: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPunishValidatorsLen(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    _validatorsContract: PromiseOrValue<string>,
    _punishContract: PromiseOrValue<string>,
    _proposalContract: PromiseOrValue<string>,
    _reservePool: PromiseOrValue<string>,
    _admin: PromiseOrValue<string>,
    _epoch: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  punish(
    _val: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  punishThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  punishValidators(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  removeThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    EPOCH(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_VALIDATORS(overrides?: CallOverrides): Promise<number>;

    PROPOSAL_CONTRACT(overrides?: CallOverrides): Promise<string>;

    PUBLISH_CONTRACT(overrides?: CallOverrides): Promise<string>;

    RESERVEPOOL_CONTRACT(overrides?: CallOverrides): Promise<string>;

    VALIDATOR_CONTRACT(overrides?: CallOverrides): Promise<string>;

    admin(overrides?: CallOverrides): Promise<string>;

    changeAdmin(
      _admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    decreaseMissedBlocksCounter(overrides?: CallOverrides): Promise<void>;

    decreaseRate(overrides?: CallOverrides): Promise<BigNumber>;

    getPunishRecord(
      val: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPunishValidatorsLen(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _validatorsContract: PromiseOrValue<string>,
      _punishContract: PromiseOrValue<string>,
      _proposalContract: PromiseOrValue<string>,
      _reservePool: PromiseOrValue<string>,
      _admin: PromiseOrValue<string>,
      _epoch: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    punish(
      _val: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    punishThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    punishValidators(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    removeThreshold(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "LogDecreaseMissedBlocksCounter()"(): LogDecreaseMissedBlocksCounterEventFilter;
    LogDecreaseMissedBlocksCounter(): LogDecreaseMissedBlocksCounterEventFilter;

    "LogPunishValidator(address,uint256)"(
      val?: PromiseOrValue<string> | null,
      time?: null
    ): LogPunishValidatorEventFilter;
    LogPunishValidator(
      val?: PromiseOrValue<string> | null,
      time?: null
    ): LogPunishValidatorEventFilter;
  };

  estimateGas: {
    EPOCH(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_VALIDATORS(overrides?: CallOverrides): Promise<BigNumber>;

    PROPOSAL_CONTRACT(overrides?: CallOverrides): Promise<BigNumber>;

    PUBLISH_CONTRACT(overrides?: CallOverrides): Promise<BigNumber>;

    RESERVEPOOL_CONTRACT(overrides?: CallOverrides): Promise<BigNumber>;

    VALIDATOR_CONTRACT(overrides?: CallOverrides): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<BigNumber>;

    changeAdmin(
      _admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    decreaseMissedBlocksCounter(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    decreaseRate(overrides?: CallOverrides): Promise<BigNumber>;

    getPunishRecord(
      val: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPunishValidatorsLen(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _validatorsContract: PromiseOrValue<string>,
      _punishContract: PromiseOrValue<string>,
      _proposalContract: PromiseOrValue<string>,
      _reservePool: PromiseOrValue<string>,
      _admin: PromiseOrValue<string>,
      _epoch: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    punish(
      _val: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    punishThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    punishValidators(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeThreshold(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    EPOCH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_VALIDATORS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PROPOSAL_CONTRACT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PUBLISH_CONTRACT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    RESERVEPOOL_CONTRACT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VALIDATOR_CONTRACT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeAdmin(
      _admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    decreaseMissedBlocksCounter(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    decreaseRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPunishRecord(
      val: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPunishValidatorsLen(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _validatorsContract: PromiseOrValue<string>,
      _punishContract: PromiseOrValue<string>,
      _proposalContract: PromiseOrValue<string>,
      _reservePool: PromiseOrValue<string>,
      _admin: PromiseOrValue<string>,
      _epoch: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    punish(
      _val: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    punishThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    punishValidators(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
